using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace Hendese.Controls
{
    /// <summary>
    /// Interaction logic for ListSections.xaml
    /// </summary>
    public partial class ListSections : UserControl
    {

        double Imin;
        double Wmin;

        public ListSections(IEnumerable<StructuralBase.Section.SectionBase> Sections, object[] parameters)
        {
            InitializeComponent();

            this.dataGrid.Items.Clear();

            this.Imin = (double)parameters[0];
            this.Wmin = (double)parameters[1];
            

            ICollectionView sectionsView =
            CollectionViewSource.GetDefaultView(Sections);

            // Set the grouping by city proprty
            sectionsView.GroupDescriptions.Add(new PropertyGroupDescription("GroupName"));

            // Set the view as the DataContext for the DataGrid
            this.dataGrid.ItemsSource = sectionsView;
            
            this.dataGrid.AutoGeneratingColumn += DataGrid_AutoGeneratingColumn;
            this.dataGrid.AutoGeneratedColumns += DataGrid_AutoGeneratedColumns;
        }

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            DataGridTextColumn iRatioCol = new DataGridTextColumn();
            iRatioCol.Header = "I Ratio";
            Binding ratioBinding = new Binding();
            ratioBinding.Mode = BindingMode.OneWay;
            ratioBinding.Converter = (IValueConverter)FindResource("RatioConverter");
            ratioBinding.ConverterParameter = this.Imin;
            iRatioCol.Binding = ratioBinding;
            this.dataGrid.Columns.Add(iRatioCol);

            DataGridTextColumn wRatioCol = new DataGridTextColumn();
            wRatioCol.Header = "W Ratio";
            Binding wRatioBinding = new Binding();
            wRatioBinding.Mode = BindingMode.OneWay;
            wRatioBinding.Converter = (IValueConverter)FindResource("WRatioConverter");
            wRatioBinding.ConverterParameter = this.Wmin;
            wRatioCol.Binding = wRatioBinding;
            this.dataGrid.Columns.Add(wRatioCol);

            //wRatioCol.SortMemberPath = "Wx";
            //iRatioCol.SortMemberPath = "I22";
            
        }

        private void DataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.PropertyName != "Name" &&
                e.PropertyName != "Area" && e.PropertyName != "W33" && e.PropertyName != "I22")
                e.Column.Visibility = Visibility.Hidden;
        }
    }
}
